name: ci

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate html
        run: npx --yes html-validate --rule "no-raw-characters:error" "site/**/*.html"
      - name: check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --include-fragments site
          fail: true
